# app/agents/meal_planner.py
import asyncio
from .base_agent import BaseAgent
from pydantic import BaseModel
from ..config import MEAL_TEMPERATURE

class MealPlanSchema(BaseModel):
    day: str
    meals: Dict[str, str]    # e.g. {"breakfast": "oats", "lunch": "salad", "dinner": "chicken"}

class MealPlannerAgent(BaseAgent):
    async def run(self, input_data):
        """
        Expected input_data:
            {
                "user_id": "...",
                "diet": {"calories": 1800, "preferences": ["vegetarian"], "allergies": ["peanut"]},
                "fallback": true/false
            }
        """
        self.log("Starting meal plan generation", meta=input_data)
        # Step 1: consult memory for preferences
        user_pref_summary = None
        if input_data.get("user_id") and self.memory:
            sims = self.memory.similarity_search(f"user:{input_data['user_id']}", k=3)
            if sims:
                user_pref_summary = [s[1].text for s in sims]

        # Step 2: craft prompt (here we simulate)
        # In real: call generation model with a JSON schema request
        await asyncio.sleep(0.05)  # simulate network latency

        # Very basic autogenerated plan for demo
        week = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
        plan = []
        for day in week:
            plan.append({
                "day": day,
                "meals": {
                    "breakfast": f"{day} yogurt + granola",
                    "lunch": f"{day} grain bowl",
                    "dinner": f"{day} roasted vegetables and protein"
                }
            })
        result = {"meal_plan": plan, "source": "simulated"}
        self.log("Meal plan ready", meta={"days": len(plan)})
        return result
